### ISSUE TITLE
`update` method is called before engine initialization

### ISSUE THREAD

**Issue by Dan-Crane** [Jerome-Saltmarsh/dart-lemon-engine#7]
update callback 
https://github.com/Jerome-Saltmarsh/dart-lemon-engine/blob/e5fb1bb53493bb088d5af1b53d22e9edb4d9b92b/lib/src/engine.dart#L612
calls before initialized canvas:
https://github.com/Jerome-Saltmarsh/dart-lemon-engine/blob/e5fb1bb53493bb088d5af1b53d22e9edb4d9b92b/lib/src/engine.dart#L516
generating a blank image: https://github.com/Jerome-Saltmarsh/dart-lemon-engine/blob/e5fb1bb53493bb088d5af1b53d22e9edb4d9b92b/lib/src/engine.dart#L1267

This bag or not?)

**Comment by Jerome-Saltmarsh** [comment]
Are you getting an exception? 

The update method should only start invocation once onInit() is finished (which is where _generateEmptyImage is called)

In any case I refactored the code to remove the late tag. (0.5.3)

**Comment by Dan-Crane** [comment]
yes, im catch exception:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_bufferImage@839291022' has not been initialized.
#0      Engine._bufferImage (package:lemon_engine/src/engine.dart)
#1      Engine.bufferImage= (package:lemon_engine/src/engine.dart:163:9)
#2      Engine.renderSprite (package:lemon_engine/src/engine.dart:887:5)
#3      BaseRender.run (package:example_lemon/systems/render.dart:30:14)
#4      EcsSystems.run (package:leo_ecs/src/systems.dart:135:22)
#5      _GameWidgetState.initState.<anonymous closure> (package:example_lemon/core/game.dart:100:17)
#6      Engine._internalOnUpdate (package:lemon_engine/src/engine.dart:612:15)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

flutter: engine.onChangedDurationPerUpdate(milliseconds: 40)
flutter: MaterialApp()
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: A Dart object attempted to access a native peer, but the native peer has been collected (nullptr). This is usually the result of calling methods on a native-backed object when the native resources have already been disposed.
#0      StateError._throwNew (dart:core-patch/errors_patch.dart:135:5)
#1      _NativeCanvas._drawRect (dart:ui/painting.dart)
#2      _NativeCanvas.drawRect (dart:ui/painting.dart:5927:5)
#3      GridPositionRenderBase.run (package:example_lemon/systems/grip_position_render.dart:32:21)
#4      EcsSystems.run (package:leo_ecs/src/systems.dart:135:22)
#5      _GameWidgetState.initState.<anonymous closure> (package:example_lemon/core/game.dart:100:17)
#6      Engine._internalOnUpdate (package:lemon_engine/src/engine.dart:612:15)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```
this happened because I accessed the kanvas in the update method.

**Comment by Dan-Crane** [comment]
Sample problem reproduction:

```dart
import 'package:flutter/material.dart';
import 'package:lemon_engine/lemon_engine.dart';

class GameWidgetV2 extends StatefulWidget {
  const GameWidgetV2({super.key});

  @override
  State<GameWidgetV2> createState() => _GameWidgetV2State();
}

class _GameWidgetV2State extends State<GameWidgetV2> {
  late final Engine engine;

  final paint = Paint()..color = Colors.green.withOpacity(0.4);

  @override
  void initState() {
    super.initState();

    engine = Engine(
      title: 'tmp',
      update: (dt) {
        // That's where i get the exception.
        engine.canvas.drawPath(
          Path()..addRect(const Rect.fromLTWH(0, 0, 100, 100)),
          paint,
        );
        // Calls engine.renderSprite also throw exception.
      },
      render: (canvas, size) {
        // This code has not eny problem.
        engine.canvas.drawPath(
          Path()..addRect(const Rect.fromLTWH(0, 0, 100, 100)),
          paint,
        );
      },
      buildUI: (_) => const SizedBox(),
    );
  }

  @override
  Widget build(BuildContext context) => engine;
}

```

**Comment by Dan-Crane** [comment]
The call to `renderSprite` and `canvas.drawPath ` was necessary to output service information, probably looks weird, but since the API allows it, I did it and got an exception:)

**Comment by Jerome-Saltmarsh** [comment]
Okay, I'll add a _initialized checker to prevent updates from being called prematurely

**Comment by Jerome-Saltmarsh** [comment]
I pushed the fix but you caught me in the middle of a refactor. 

I'm changing over the overall architecture to an inheritance based approach, just more simple overall. 

Its pretty straight forward to port, should only take a few minutes.

I updated the example project to use the latest version 

https://github.com/Jerome-Saltmarsh/dart-lemon-engine-example/blob/master/lib/example.dart

lemon_engine 0.5.7

(sorry for the inconvenience)
